preset: psr2

enabled:
  - binary_operator_spaces
  - blank_line_after_opening_tag
  - blank_line_before_declare
  - blank_line_before_return
  - blank_line_before_try
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - combine_nested_dirname
  - comment_to_phpdoc
  - compact_nullable_typehint
  - concat_with_spaces
  - const_visibility_required
  - declare_strict_types
  - dir_constant
  - explicit_string_variable
  - final_internal_class
  - fully_qualified_strict_types
  - function_to_constant
  - function_typehint_space
  - hash_to_slash_comment
  - implode_call
  - include
  - is_null
  - linebreak_after_opening_tag
  - logical_operators
  - lowercase_static_reference
  - magic_constant_casing
  - magic_method_casing
  - method_separation
  - modernize_types_casting
  - multiline_comment_opening_closing
  - native_function_casing
  - no_alias_functions
  - no_alternative_syntax
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_null_property_initialization
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_unreachable_default_argument_value
  - no_unset_on_property
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - non_printable_character
  - normalize_index_brace
  - not_operator_with_successor_space
  - object_operator_without_whitespace
  - phpdoc_add_missing_param_annotation
  - phpdoc_indent
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_types
  - property_separation
  - self_accessor
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
  - standardize_not_equals
  - ternary_operator_spaces
  - ternary_to_null_coalescing
  - trailing_comma_in_multiline_array
  - whitespace_after_comma_in_array

risky: true
